### DISCUSSION TITLE
Error: Opencl torch.cuda.OutOfMemoryError: HIP out of memory. Tried to allocate 2.01 GiB. GPU

### DISCUSSION THREAD

**Discussion by grahamberends** [ROCm/ROCm#3459] [General]
Dear All

Please help me with this Out of Memory issue.

I'm trying to use Whisper to convert an mp3 audio file to text.
I ran a sample python program calling a local 240-second audio track, see below. It failed with an Out of Memory message.

This is the Error Message:

> /home/graham/.local/lib/python3.12/site-packages/transformers/models/whisper/modeling_whisper.py:694: 
> UserWarning: 1Torch was not compiled with memory efficient attention. 
> (Triggered internally at ../aten/src/ATen/native/transformers/hip/sdp_utils.cpp:505.)
>  ... 
> torch.cuda.OutOfMemoryError: HIP out of memory. Tried to allocate 2.01 GiB. GPU
> 

**Questions**:
1) How do I go about solving this issue?
2) UserWarning: 1Torch was not compiled with memory efficient attention. Is this something I can influence?
3) Is opencl the problem?

Below  are details of the the program code and Info on my Installation: System, CPU, GPU, cuda/torch/opencl, ROCm rpms, dmesg (firmware), dmesg (amdgpu) and rocm-clinfo.

Look forward to your replies.
In anticipation
Graham

= = = = = = = = = = = = = = = = = = = = =
Info about Program and Installation
= = = = = = = = = = = = = = = = = = = = =

$ python sample_py_with_whisper_largev3_20240306_v2.py
```
#!/usr/bin/env python
import os,sys
import subprocess
import glob
from os import path

f = open('arecord_EM_202400723_18100.txt','w')
sys.stdout = f

import torch
from transformers import AutoModelForSpeechSeq2Seq, AutoProcessor, pipeline
from datasets import load_dataset

device = "cuda:0" if torch.cuda.is_available() else "cpu"
torch_dtype = torch.float32

print(f"Using device: {device}")

model_id = "openai/whisper-large-v3"

model = AutoModelForSpeechSeq2Seq.from_pretrained(
    model_id, torch_dtype=torch_dtype, low_cpu_mem_usage=False, use_safetensors=True
)
model.to(device)

processor = AutoProcessor.from_pretrained(model_id)

pipe = pipeline(
    "automatic-speech-recognition",
    model=model,
    tokenizer=processor.tokenizer,
    feature_extractor=processor.feature_extractor,
    max_new_tokens=128,
    chunk_length_s=30,
    batch_size=16,
    return_timestamps=True,
    torch_dtype=torch_dtype,
    device=device,
    generate_kwargs={"language": "english"},
)

dataset = load_dataset("distil-whisper/librispeech_long", "clean", split="validation")
sample = dataset[0]["audio"]

result = pipe("240_test_audio_file.mp3")
print(result["text"])`
```
My system specs are as follows:
uname -a
  Linux fedora 6.9.9-200.fc40.x86_64 ... x86_64 GNU/Linux
CPU: rocminfo
  Name:                    12th Gen Intel(R) Core(TM) i9-12900K
  
GPU: rocminfo
  Name:                    gfx1100                            
  Marketing Name:          AMD Radeon RX 7600                 
  Memory                   7.98GiB
  
cuda:
PyTorch 2.3.0 for ROCm 6.0.0.
$ pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm6.0

Opencl and ROCm rpms
```
$ rpm -qa | grep opencl
	opencl-filesystem-1.0-20.fc40.noarch
	rocm-opencl-6.0.2-2.fc40.x86_64
$ rpm -qa | grep rocm
	hsakmt-1.0.6-38.rocm6.0.0.fc40.x86_64
	rocm-runtime-6.0.0-3.fc40.x86_64
	rocminfo-6.0.2-2.fc40.x86_64
	rocm-comgr-17.1-5.fc40.x86_64
	rocm-opencl-6.0.2-2.fc40.x86_64
	rocm-clinfo-6.0.2-2.fc40.x86_64
	rocm-device-libs-17.2-3.fc40.x86_64
	rocm-hip-6.0.2-2.fc40.x86_64

```
dmesg Firmware:
```
$ sudo dmesg | grep firmware
	[    4.120547] i915 0000:00:02.0: [drm] Finished loading DMC firmware i915/adls_dmc_ver2_01.bin (v2.1)
	[    4.456578] i915 0000:00:02.0: [drm] GT0: GuC firmware i915/tgl_guc_70.bin version 70.20.0
	[    4.456581] i915 0000:00:02.0: [drm] GT0: HuC firmware i915/tgl_huc.bin version 7.9.3
	[    5.447097] [drm] Loading DMUB firmware via PSP: version=0x07002A00
	[    5.447198] [drm] Found VCN firmware Version ENC: 1.21 DEC: 8 VEP: 0 Revision: 1
	[    5.447201] amdgpu 0000:03:00.0: amdgpu: Will use PSP to load VCN firmware
	[    7.518689] iwlwifi 0000:00:14.3: loaded firmware version 89.202a2f7b.0 so-a0-gf-a0-89.ucode op_mode iwlmvm
	[    7.527974] Bluetooth: hci0: Found device firmware: intel/ibt-1040-0041.sfi
	[ 3370.636538] i915 0000:00:02.0: [drm] GT0: GuC firmware i915/tgl_guc_70.bin version 70.20.0
	[ 3370.636544] i915 0000:00:02.0: [drm] GT0: HuC firmware i915/tgl_huc.bin version 7.9.3
	[ 4274.273050] i915 0000:00:02.0: [drm] GT0: GuC firmware i915/tgl_guc_70.bin version 70.20.0
	[ 4274.273055] i915 0000:00:02.0: [drm] GT0: HuC firmware i915/tgl_huc.bin version 7.9.3
```

dmesg amdgpu:
```
$ sudo dmesg | grep amdgpu
	[    5.378506] [drm] amdgpu kernel modesetting enabled.
	[    5.378566] amdgpu: Virtual CRAT table created for CPU
	[    5.378572] amdgpu: Topology: Add CPU node
	[    5.378665] amdgpu 0000:03:00.0: enabling device (0006 -> 0007)
	[    5.381951] amdgpu 0000:03:00.0: amdgpu: Fetched VBIOS from VFCT
	[    5.381953] amdgpu: ATOM BIOS: 113-APM6209-101
	[    5.406026] amdgpu 0000:03:00.0: amdgpu: CP RS64 enable
	[    5.429229] amdgpu 0000:03:00.0: [drm:jpeg_v4_0_early_init [amdgpu]] JPEG decode is enabled in VM mode
	[    5.446216] amdgpu 0000:03:00.0: vgaarb: deactivate vga console
	[    5.446219] amdgpu 0000:03:00.0: amdgpu: Trusted Memory Zone (TMZ) feature not supported
	[    5.446257] amdgpu 0000:03:00.0: amdgpu: VRAM: 8176M 0x0000008000000000 - 0x00000081FEFFFFFF (8176M used)
	[    5.446259] amdgpu 0000:03:00.0: amdgpu: GART: 512M 0x00007FFF00000000 - 0x00007FFF1FFFFFFF
	[    5.446382] [drm] amdgpu: 8176M of VRAM memory ready
	[    5.446382] [drm] amdgpu: 32031M of GTT memory ready.
	[    5.447201] amdgpu 0000:03:00.0: amdgpu: Will use PSP to load VCN firmware
	[    5.504245] amdgpu 0000:03:00.0: amdgpu: reserve 0x1300000 from 0x81fc000000 for PSP TMR
	[    5.597435] amdgpu 0000:03:00.0: amdgpu: RAS: optional ras ta ucode is not available
	[    5.604925] amdgpu 0000:03:00.0: amdgpu: RAP: optional rap ta ucode is not available
	[    5.604926] amdgpu 0000:03:00.0: amdgpu: SECUREDISPLAY: securedisplay ta ucode is not available
	[    5.604972] amdgpu 0000:03:00.0: amdgpu: smu driver if version = 0x00000035, smu fw if version = 0x00000040, smu fw program = 0, smu fw version = 0x00525b00 (82.91.0)
	[    5.604974] amdgpu 0000:03:00.0: amdgpu: SMU driver if version not matched
	[    5.662003] amdgpu 0000:03:00.0: amdgpu: SMU is initialized successfully!
	[    5.736540] amdgpu 0000:03:00.0: [drm:jpeg_v4_0_hw_init [amdgpu]] JPEG decode initialized successfully.
	[    5.773920] amdgpu: HMM registered 8176MB device memory
	[    5.775476] kfd kfd: amdgpu: Allocated 3969056 bytes on gart
	[    5.775485] kfd kfd: amdgpu: Total number of KFD nodes to be created: 1
	[    5.775516] amdgpu: Virtual CRAT table created for GPU
	[    5.775564] amdgpu: Topology: Add dGPU node [0x7480:0x1002]
	[    5.775565] kfd kfd: amdgpu: added device 1002:7480
	[    5.775575] amdgpu 0000:03:00.0: amdgpu: SE 2, SH per SE 2, CU per SH 8, active_cu_number 32
	[    5.775577] amdgpu 0000:03:00.0: amdgpu: ring gfx_0.0.0 uses VM inv eng 0 on hub 0
	[    5.775578] amdgpu 0000:03:00.0: amdgpu: ring comp_1.0.0 uses VM inv eng 1 on hub 0
	[    5.775578] amdgpu 0000:03:00.0: amdgpu: ring comp_1.1.0 uses VM inv eng 4 on hub 0
	[    5.775579] amdgpu 0000:03:00.0: amdgpu: ring comp_1.2.0 uses VM inv eng 6 on hub 0
	[    5.775579] amdgpu 0000:03:00.0: amdgpu: ring comp_1.3.0 uses VM inv eng 7 on hub 0
	[    5.775580] amdgpu 0000:03:00.0: amdgpu: ring comp_1.0.1 uses VM inv eng 8 on hub 0
	[    5.775580] amdgpu 0000:03:00.0: amdgpu: ring comp_1.1.1 uses VM inv eng 9 on hub 0
	[    5.775580] amdgpu 0000:03:00.0: amdgpu: ring comp_1.2.1 uses VM inv eng 10 on hub 0
	[    5.775581] amdgpu 0000:03:00.0: amdgpu: ring comp_1.3.1 uses VM inv eng 11 on hub 0
	[    5.775581] amdgpu 0000:03:00.0: amdgpu: ring sdma0 uses VM inv eng 12 on hub 0
	[    5.775582] amdgpu 0000:03:00.0: amdgpu: ring sdma1 uses VM inv eng 13 on hub 0
	[    5.775582] amdgpu 0000:03:00.0: amdgpu: ring vcn_unified_0 uses VM inv eng 0 on hub 8
	[    5.775583] amdgpu 0000:03:00.0: amdgpu: ring jpeg_dec uses VM inv eng 1 on hub 8
	[    5.775583] amdgpu 0000:03:00.0: amdgpu: ring mes_kiq_3.1.0 uses VM inv eng 14 on hub 0
	[    5.778868] amdgpu 0000:03:00.0: amdgpu: Using BACO for runtime pm
	[    5.779057] [drm] Initialized amdgpu 3.57.0 20150101 for 0000:03:00.0 on minor 2
	[    5.788395] fbcon: amdgpudrmfb (fb0) is primary device
	[    5.788397] amdgpu 0000:03:00.0: [drm] fb0: amdgpudrmfb frame buffer device
	[    6.190876] amdgpu 0000:03:00.0: [drm] REG_WAIT timeout 1us * 150000 tries - optc32_disable_crtc line:196
	[    7.556209] snd_hda_intel 0000:03:00.1: bound 0000:03:00.0 (ops amdgpu_dm_audio_component_bind_ops [amdgpu])
	[ 3369.714404] amdgpu 0000:03:00.0: amdgpu: MODE1 reset
	[ 3369.714416] amdgpu 0000:03:00.0: amdgpu: GPU mode1 reset
	[ 3369.714509] amdgpu 0000:03:00.0: amdgpu: GPU smu mode1 reset
	[ 3370.620943] amdgpu 0000:03:00.0: amdgpu: PSP is resuming...
	[ 3370.690202] amdgpu 0000:03:00.0: amdgpu: reserve 0x1300000 from 0x81fc000000 for PSP TMR
	[ 3370.784335] amdgpu 0000:03:00.0: amdgpu: RAS: optional ras ta ucode is not available
	[ 3370.792226] amdgpu 0000:03:00.0: amdgpu: RAP: optional rap ta ucode is not available
	[ 3370.792230] amdgpu 0000:03:00.0: amdgpu: SECUREDISPLAY: securedisplay ta ucode is not available
	[ 3370.792237] amdgpu 0000:03:00.0: amdgpu: SMU is resuming...
	[ 3370.792246] amdgpu 0000:03:00.0: amdgpu: smu driver if version = 0x00000035, smu fw if version = 0x00000040, smu fw program = 0, smu fw version = 0x00525b00 (82.91.0)
	[ 3370.792255] amdgpu 0000:03:00.0: amdgpu: SMU driver if version not matched
	[ 3370.836089] amdgpu 0000:03:00.0: amdgpu: SMU is resumed successfully!
	[ 3370.879784] amdgpu 0000:03:00.0: [drm:jpeg_v4_0_hw_init [amdgpu]] JPEG decode initialized successfully.
	[ 3370.880194] amdgpu 0000:03:00.0: amdgpu: ring gfx_0.0.0 uses VM inv eng 0 on hub 0
	[ 3370.880196] amdgpu 0000:03:00.0: amdgpu: ring comp_1.0.0 uses VM inv eng 1 on hub 0
	[ 3370.880196] amdgpu 0000:03:00.0: amdgpu: ring comp_1.1.0 uses VM inv eng 4 on hub 0
	[ 3370.880197] amdgpu 0000:03:00.0: amdgpu: ring comp_1.2.0 uses VM inv eng 6 on hub 0
	[ 3370.880198] amdgpu 0000:03:00.0: amdgpu: ring comp_1.3.0 uses VM inv eng 7 on hub 0
	[ 3370.880198] amdgpu 0000:03:00.0: amdgpu: ring comp_1.0.1 uses VM inv eng 8 on hub 0
	[ 3370.880199] amdgpu 0000:03:00.0: amdgpu: ring comp_1.1.1 uses VM inv eng 9 on hub 0
	[ 3370.880199] amdgpu 0000:03:00.0: amdgpu: ring comp_1.2.1 uses VM inv eng 10 on hub 0
	[ 3370.880200] amdgpu 0000:03:00.0: amdgpu: ring comp_1.3.1 uses VM inv eng 11 on hub 0
	[ 3370.880200] amdgpu 0000:03:00.0: amdgpu: ring sdma0 uses VM inv eng 12 on hub 0
	[ 3370.880201] amdgpu 0000:03:00.0: amdgpu: ring sdma1 uses VM inv eng 13 on hub 0
	[ 3370.880201] amdgpu 0000:03:00.0: amdgpu: ring vcn_unified_0 uses VM inv eng 0 on hub 8
	[ 3370.880202] amdgpu 0000:03:00.0: amdgpu: ring jpeg_dec uses VM inv eng 1 on hub 8
	[ 3370.880202] amdgpu 0000:03:00.0: amdgpu: ring mes_kiq_3.1.0 uses VM inv eng 14 on hub 0
	[ 4273.369931] amdgpu 0000:03:00.0: amdgpu: MODE1 reset
	[ 4273.369942] amdgpu 0000:03:00.0: amdgpu: GPU mode1 reset
	[ 4273.370041] amdgpu 0000:03:00.0: amdgpu: GPU smu mode1 reset
	[ 4274.260210] amdgpu 0000:03:00.0: amdgpu: PSP is resuming...
	[ 4274.325638] amdgpu 0000:03:00.0: amdgpu: reserve 0x1300000 from 0x81fc000000 for PSP TMR
	[ 4274.419552] amdgpu 0000:03:00.0: amdgpu: RAS: optional ras ta ucode is not available
	[ 4274.427190] amdgpu 0000:03:00.0: amdgpu: RAP: optional rap ta ucode is not available
	[ 4274.427193] amdgpu 0000:03:00.0: amdgpu: SECUREDISPLAY: securedisplay ta ucode is not available
	[ 4274.427199] amdgpu 0000:03:00.0: amdgpu: SMU is resuming...
	[ 4274.427212] amdgpu 0000:03:00.0: amdgpu: smu driver if version = 0x00000035, smu fw if version = 0x00000040, smu fw program = 0, smu fw version = 0x00525b00 (82.91.0)
	[ 4274.427222] amdgpu 0000:03:00.0: amdgpu: SMU driver if version not matched
	[ 4274.469256] amdgpu 0000:03:00.0: amdgpu: SMU is resumed successfully!
	[ 4274.512890] amdgpu 0000:03:00.0: [drm:jpeg_v4_0_hw_init [amdgpu]] JPEG decode initialized successfully.
	[ 4274.513329] amdgpu 0000:03:00.0: amdgpu: ring gfx_0.0.0 uses VM inv eng 0 on hub 0
	[ 4274.513331] amdgpu 0000:03:00.0: amdgpu: ring comp_1.0.0 uses VM inv eng 1 on hub 0
	[ 4274.513331] amdgpu 0000:03:00.0: amdgpu: ring comp_1.1.0 uses VM inv eng 4 on hub 0
	[ 4274.513332] amdgpu 0000:03:00.0: amdgpu: ring comp_1.2.0 uses VM inv eng 6 on hub 0
	[ 4274.513332] amdgpu 0000:03:00.0: amdgpu: ring comp_1.3.0 uses VM inv eng 7 on hub 0
	[ 4274.513333] amdgpu 0000:03:00.0: amdgpu: ring comp_1.0.1 uses VM inv eng 8 on hub 0
	[ 4274.513333] amdgpu 0000:03:00.0: amdgpu: ring comp_1.1.1 uses VM inv eng 9 on hub 0
	[ 4274.513334] amdgpu 0000:03:00.0: amdgpu: ring comp_1.2.1 uses VM inv eng 10 on hub 0
	[ 4274.513334] amdgpu 0000:03:00.0: amdgpu: ring comp_1.3.1 uses VM inv eng 11 on hub 0
	[ 4274.513335] amdgpu 0000:03:00.0: amdgpu: ring sdma0 uses VM inv eng 12 on hub 0
	[ 4274.513335] amdgpu 0000:03:00.0: amdgpu: ring sdma1 uses VM inv eng 13 on hub 0
	[ 4274.513336] amdgpu 0000:03:00.0: amdgpu: ring vcn_unified_0 uses VM inv eng 0 on hub 8
	[ 4274.513337] amdgpu 0000:03:00.0: amdgpu: ring jpeg_dec uses VM inv eng 1 on hub 8
	[ 4274.513337] amdgpu 0000:03:00.0: amdgpu: ring mes_kiq_3.1.0 uses VM inv eng 14 on hub 0
```

rocm-clinfo
```
$ rocm-clinfo
Number of platforms:				 1
  Platform Profile:				 FULL_PROFILE
  Platform Version:				 OpenCL 2.1 AMD-APP (3602.0)
  Platform Name:				 AMD Accelerated Parallel Processing
  Platform Vendor:				 Advanced Micro Devices, Inc.
  Platform Extensions:				 cl_khr_icd cl_amd_event_callback 

  Platform Name:				 AMD Accelerated Parallel Processing
  Number of devices:				 1
  Device Type:					 CL_DEVICE_TYPE_GPU
  Vendor ID:					 1002h
  Board name:					 AMD Radeon RX 7600
  Device Topology:				 PCI[ B#3, D#0, F#0 ]
  Max compute units:				 16
  Max work items dimensions:			 3
    Max work items[0]:				 1024
    Max work items[1]:				 1024
    Max work items[2]:				 1024
  Max work group size:				 256
  Preferred vector width char:			 4
  Preferred vector width short:			 2
  Preferred vector width int:			 1
  Preferred vector width long:			 1
  Preferred vector width float:			 1
  Preferred vector width double:		 1
  Native vector width char:			 4
  Native vector width short:			 2
  Native vector width int:			 1
  Native vector width long:			 1
  Native vector width float:			 1
  Native vector width double:			 1
  Max clock frequency:				 2356Mhz
  Address bits:					 64
  Max memory allocation:			 7287183768
  Image support:				 Yes
  Max number of images read arguments:		 128
  Max number of images write arguments:		 8
  Max image 2D width:				 16384
  Max image 2D height:				 16384
  Max image 3D width:				 16384
  Max image 3D height:				 16384
  Max image 3D depth:				 8192
  Max samplers within kernel:			 16
  Max size of kernel argument:			 1024
  Alignment (bits) of base address:		 1024
  Minimum alignment (bytes) for any datatype:	 128
  Single precision floating point capability
    Denorms:					 Yes
    Quiet NaNs:					 Yes
    Round to nearest even:			 Yes
    Round to zero:				 Yes
    Round to +ve and infinity:			 Yes
    IEEE754-2008 fused multiply-add:		 Yes
  Cache type:					 Read/Write
  Cache line size:				 64
  Cache size:					 32768
  Global memory size:				 8573157376
  Constant buffer size:				 7287183768
  Max number of constant args:			 8
  Local memory type:				 Scratchpad
  Local memory size:				 65536
  Max pipe arguments:				 16
  Max pipe active reservations:			 16
  Max pipe packet size:				 2992216472
  Max global variable size:			 7287183768
  Max global variable preferred total size:	 8573157376
  Max read/write image args:			 64
  Max on device events:				 1024
  Queue on device max size:			 8388608
  Max on device queues:				 1
  Queue on device preferred size:		 262144
  SVM capabilities:				 
    Coarse grain buffer:			 Yes
    Fine grain buffer:				 Yes
    Fine grain system:				 No
    Atomics:					 No
  Preferred platform atomic alignment:		 0
  Preferred global atomic alignment:		 0
  Preferred local atomic alignment:		 0
  Kernel Preferred work group size multiple:	 32
  Error correction support:			 0
  Unified memory for Host and Device:		 0
  Profiling timer resolution:			 1
  Device endianess:				 Little
  Available:					 Yes
  Compiler available:				 Yes
  Execution capabilities:				 
    Execute OpenCL kernels:			 Yes
    Execute native function:			 No
  Queue on Host properties:				 
    Out-of-Order:				 No
    Profiling :					 Yes
  Queue on Device properties:				 
    Out-of-Order:				 Yes
    Profiling :					 Yes
  Platform ID:					 0x7f5c7691c808
  Name:						 gfx1100
  Vendor:					 Advanced Micro Devices, Inc.
  Device OpenCL C version:			 OpenCL C 2.0 
  Driver version:				 3602.0 (HSA1.1,LC)
  Profile:					 FULL_PROFILE
  Version:					 OpenCL 2.0 
  Extensions:					 cl_khr_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_gl_sharing cl_amd_device_attribute_query cl_amd_media_ops cl_amd_media_ops2 cl_khr_image2d_from_buffer cl_khr_subgroups cl_khr_depth_images cl_amd_copy_buffer_p2p cl_amd_assembly_program 

```

**Comment by grahamberends** [comment]
Dear All
I have solved this problem.
My questions were:
    How do I go about solving this issue?
       See below.
    UserWarning: 1Torch was not compiled with memory efficient attention. Is this something I can influence?
       Answer: Torch gives this warning every time. It is not a problem - slightly irritating now.
    Is opencl the problem?
      No. It may be a bit slower but it works.

I solved this problem with the following changes:
1) Freeing up memory prior to starting to use the GPU: # Free Up GPU Memory
      os.system('rocm-smi')
      torch.cuda.empty_cache() 
2)  Using less accurate floating point
      torch_dtype = torch.float16
3) Using a smaller model:
      model-id = "openai/whisper-tiny" 
4) Using different tensors in AutoModelForSpeechSeq2Seq.from_pretrained()
      use_safetensors=True
5) In the pipeline() function using smaller batch and chunking sizes, examples:
          max_new_tokens=64,  # Reduced from 128
         chunk_length_s=5,  # Reduced from 30
         batch_size=1,  # Reduced from either 32 or 16
6)  Others are recommended like control the input file by external batching and/or streaming. [I have not yet needed to consider these ideas.]

Results: After these changes my GPU converted a 90 minute mp3 in the order of 20-30 seconds - I didn't time it. See the loading/performance display image, attached.

![Screenshot_GPU_performance_20240727](https://github.com/user-attachments/assets/dce6bc16-b36b-416d-bd7a-07e8ebd76d21)

Conclusion: The key to is using Whisper-tiny and feeding the pipeline() to the GPU with smaller chunks.
Observation: I do not know which changes had the most effect. I will try removing some of them and see what happens. 

Thank you all. Hope this is useful.
Regards
Graham

**Comment by grahamberends** [comment]
Closed. See closing comments above.
Thanks
