### ISSUE TITLE
ROCm not uninstalling and messing up pytorch-cpu RX6600XT

### ISSUE THREAD

**Issue by march-o** [ROCm/ROCm#1727]
So I recently installed ROCm and anaconda and pytorch on new linux dualboot. But after finding out that my gpu is not compatible, I uninstalled ROCm and that version of pytorch and even reinstalled anaconda. But after installing pytorch-cpu and running in python it shows:
/opt/amdgpu/share/libdrm/amdgpu.ids: No such file or directory
/opt/amdgpu/share/libdrm/amdgpu.ids: No such file or directory
"hipErrorNoBinaryForGpu: Unable to find code object for all current devices!"

I dont know what to do, I have gone through the uninstall proceedure 3 times and it still isnt working. 

My gpu: RX6600XT(I understand that it is not supported but I thought I'll try to install since other similar gpus worked.)
ROCm version: 5.0.0
Rocm pytorch version: pip3 install torch torchvision --extra-index-url https://download.pytorch.org/whl/rocm4.5.2

After running sudo amdgpu-uninstall : 
sudo: amdgpu-uninstall: command not found

After running sudo apt autoremove amdgpu-dkms or sudo apt autoremove rocm-core: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package amdgpu-dkms

At location /etc/apt/sources.list.d is no amd or rocm repository.

At this point I am considering just reinstalling linux.

I am new to linux and this stuff so sorry in advance if I accidantly messed up something simple.
Thanks.

**Comment by ffleader1** [comment]
It seems that you tried to install Pytorch on Global Environment. This is 99% NOT recommended. In Python, always use virtual environment.

**Comment by MJ-Osis** [comment]
I didn't, I used anaconda. I kind of solved the issue by installing PyTorch on an environment with a different python. But python 3.8 now is dead on that pc so that's sad. But thanks for the concern!

**Comment by ffleader1** [comment]
> @ffleader1. I didn't, I used anaconda. My first troubleshooting steps were to reinstall anaconda. I kind of solved the issue by installing PyTorch on an environment with a different python. But python 3.8 now is dead on that pc so that's sad. But thanks for the concern!

I think I was being more or less rude and all, so sorry about that. Anyway, are you a windows guy (as you said you were not familiar with Linux and all). I think while it may sound ridiculous, installing Rocm on Windows has more potential than on Linux.

**Comment by MJ-Osis** [comment]
> > @ffleader1. I didn't, I used anaconda. My first troubleshooting steps were to reinstall anaconda. I kind of solved the issue by installing PyTorch on an environment with a different python. But python 3.8 now is dead on that pc so that's sad. But thanks for the concern!
> 
> I think I was being more or less rude and all, so sorry about that. Anyway, are you a windows guy (as you said you were not familiar with Linux and all). I think while it may sound ridiculous, installing Rocm on Windows has more potential than on Linux.

That does sound ridiculous, but I might try it someday. I'm moving most of my coding stuff on Linux and I like it better there for that stuff(obviously). Also, I have a great setup at my new job with Nvidia, but I just really wanted to be able to make small personal projects at home, but I can't do that without a gpu(apart from colab). I guess 6600XT just didn't make the cut :(, at least just for now I hope

**Comment by ffleader1** [comment]
> 

While I did not try (I own no Navi card), it seems that you can have a non-Navi 23 card supported by recompiling rocm, but replacing the device string. So for example, the 6800 is Navi 21, gfx1031, but the 6600XT is Navi 23, gfx1033. 

So what one out to be doing is string replace gfx1031 to gfx1033 and recompile Rocm. I have a Vega 56 only so I can't really test it. It just that I have been looking up this topic and, yeah, people have tried and it worked, supposedly.

Also, microsoft does have this Antares thing.
https://github.com/microsoft/antares
Quite honestly it is ridiculously easy to install and works with everything. Basically 1-liner on WSL:

`pip3 install --upgrade antares
BACKEND=c-rocm_win64 antares`

Again, supposedly, this should be enough, and in the future, and Antares would probably not even require Wsl.

All in all, I really want to see AMD thrive in ML space and they are doing great in constantly shooting themselves in the foot.

**Comment by Kayzwer** [comment]
cp /usr/share/libdrm/amdgpu.ids /opt/amdgpu/share/libdrm/

**Comment by hongxiayang** [comment]
Looks like your gpu type is not in the official supported list:
https://rocm.docs.amd.com/en/latest/release/gpu_os_support.html

Can you run
```
rocminfo | grep gfx
```

**Comment by abhimeda** [comment]
@march-o  Hi, was the above answer helpful? If so, can we close this ticket?

**Comment by nartmada** [comment]
Closing the ticket.  @march-o, please reopen if you still need guidance on your issue.  Thank you.
