### ISSUE TITLE
[Issue]: Windows hip error 'no ROCm-capable device is detected'

### ISSUE THREAD

**Issue by EmotionIce** [ROCm/ROCm#2941]
### Problem Description

After installing all HIP SDK with all its options successfully and setting up the system environment variables,
I get hipErrorNoDevice when running the `hipinfo` command or when trying to use hip:

```
:4:C:\constructicon\builds\gfx\two\23.30\drivers\compute\clr\rocclr\platform\runtime.cpp:83  : 1256747841 us: [pid:20784 tid:0x9b0] init
:3:C:\constructicon\builds\gfx\two\23.30\drivers\compute\clr\hipamd\src\hip_context.cpp:48  : 1256747970 us: [pid:20784 tid:0x9b0] Direct Dispatch: 0
:3:C:\constructicon\builds\gfx\two\23.30\drivers\compute\clr\hipamd\src\hip_device_runtime.cpp:546 : 1256748073 us: [pid:20784 tid:0x9b0]  hipGetDeviceCount ( 0000000801EFFA3C )
:3:C:\constructicon\builds\gfx\two\23.30\drivers\compute\clr\hipamd\src\hip_device_runtime.cpp:548 : 1256748170 us: [pid:20784 tid:0x9b0] hipGetDeviceCount: Returned hipErrorNoDevice :
:3:C:\constructicon\builds\gfx\two\23.30\drivers\compute\clr\hipamd\src\hip_device_runtime.cpp:546 : 1256748258 us: [pid:20784 tid:0x9b0]  hipGetDeviceCount ( 0000000801EFFA3C )
:3:C:\constructicon\builds\gfx\two\23.30\drivers\compute\clr\hipamd\src\hip_device_runtime.cpp:548 : 1256748345 us: [pid:20784 tid:0x9b0] hipGetDeviceCount: Returned hipErrorNoDevice :
:3:C:\constructicon\builds\gfx\two\23.30\drivers\compute\clr\hipamd\src\hip_device_runtime.cpp:546 : 1256748410 us: [pid:20784 tid:0x9b0]  hipGetDeviceCount ( 0000000801EFFA3C )
:3:C:\constructicon\builds\gfx\two\23.30\drivers\compute\clr\hipamd\src\hip_device_runtime.cpp:548 : 1256748470 us: [pid:20784 tid:0x9b0] hipGetDeviceCount: Returned hipErrorNoDevice :
error: 'no ROCm-capable device is detected'(100) at C:\constructicon\builds\gfx\two\23.30\drivers\compute\hip-tests\samples\1_Utils\hipInfo\hipInfo.cpp:205
error: API returned error code.
error: TEST FAILED
```

The GPU is recognized by the system and usually works.

### Operating System

Windows 11 Pro 10.0.22621 (22H2)

### CPU

Intel(R) Core(TM) i7-8086K CPU @ 4.00GHz

### GPU

AMD Radeon RX 7900 XT

### ROCm Version

ROCm 5.7.1

### ROCm Component

HIP

### Steps to Reproduce

I uninstalled all existing HIP and AMD drivers and downgraded from windows 23H2 to 22H2 (attempting to fix this). 
Downloaded HIP SDK 5.7.1 for Windows 10 & 11 and installed it.
Then I set up the system environment variables to be `HIP_PATH=C:\Program Files\AMD\ROCm\5.7\`, `HIP_PATH_57=C:\Program Files\AMD\ROCm\5.7\`, `HIP_VISIBLE_DEVICES=1` and in the Path variable I added `C:\Program Files\AMD\ROCm\5.7\bin` and `%HIP_PATH%bin`.

**Comment by harkgill-amd** [comment]
Hi @EmotionIce, are you still experiencing this issue with HIP SDK 5.7.1?

**Comment by V6ser** [comment]
I 

> ### Problem Description
> After installing all HIP SDK with all its options successfully and setting up the system environment variables, I get hipErrorNoDevice when running the `hipinfo` command or when trying to use hip:
> 
> ```
> :4:C:\constructicon\builds\gfx\two\23.30\drivers\compute\clr\rocclr\platform\runtime.cpp:83  : 1256747841 us: [pid:20784 tid:0x9b0] init
> :3:C:\constructicon\builds\gfx\two\23.30\drivers\compute\clr\hipamd\src\hip_context.cpp:48  : 1256747970 us: [pid:20784 tid:0x9b0] Direct Dispatch: 0
> :3:C:\constructicon\builds\gfx\two\23.30\drivers\compute\clr\hipamd\src\hip_device_runtime.cpp:546 : 1256748073 us: [pid:20784 tid:0x9b0]  hipGetDeviceCount ( 0000000801EFFA3C )
> :3:C:\constructicon\builds\gfx\two\23.30\drivers\compute\clr\hipamd\src\hip_device_runtime.cpp:548 : 1256748170 us: [pid:20784 tid:0x9b0] hipGetDeviceCount: Returned hipErrorNoDevice :
> :3:C:\constructicon\builds\gfx\two\23.30\drivers\compute\clr\hipamd\src\hip_device_runtime.cpp:546 : 1256748258 us: [pid:20784 tid:0x9b0]  hipGetDeviceCount ( 0000000801EFFA3C )
> :3:C:\constructicon\builds\gfx\two\23.30\drivers\compute\clr\hipamd\src\hip_device_runtime.cpp:548 : 1256748345 us: [pid:20784 tid:0x9b0] hipGetDeviceCount: Returned hipErrorNoDevice :
> :3:C:\constructicon\builds\gfx\two\23.30\drivers\compute\clr\hipamd\src\hip_device_runtime.cpp:546 : 1256748410 us: [pid:20784 tid:0x9b0]  hipGetDeviceCount ( 0000000801EFFA3C )
> :3:C:\constructicon\builds\gfx\two\23.30\drivers\compute\clr\hipamd\src\hip_device_runtime.cpp:548 : 1256748470 us: [pid:20784 tid:0x9b0] hipGetDeviceCount: Returned hipErrorNoDevice :
> error: 'no ROCm-capable device is detected'(100) at C:\constructicon\builds\gfx\two\23.30\drivers\compute\hip-tests\samples\1_Utils\hipInfo\hipInfo.cpp:205
> error: API returned error code.
> error: TEST FAILED
> ```
> 
> The GPU is recognized by the system and usually works.
> 
> ### Operating System
> Windows 11 Pro 10.0.22621 (22H2)
> 
> ### CPU
> Intel(R) Core(TM) i7-8086K CPU @ 4.00GHz
> 
> ### GPU
> AMD Radeon RX 7900 XT
> 
> ### ROCm Version
> ROCm 5.7.1
> 
> ### ROCm Component
> HIP
> 
> ### Steps to Reproduce
> I uninstalled all existing HIP and AMD drivers and downgraded from windows 23H2 to 22H2 (attempting to fix this). Downloaded HIP SDK 5.7.1 for Windows 10 & 11 and installed it. Then I set up the system environment variables to be `HIP_PATH=C:\Program Files\AMD\ROCm\5.7\`, `HIP_PATH_57=C:\Program Files\AMD\ROCm\5.7\`, `HIP_VISIBLE_DEVICES=1` and in the Path variable I added `C:\Program Files\AMD\ROCm\5.7\bin` and `%HIP_PATH%bin`.
> 
> ### (Optional for Linux users) Output of /opt/rocm/bin/rocminfo --support
> _No response_
> 
> ### Additional Information
> _No response_

Your issue will persist. This problem had bugged me for some time now. Trying to get WSL to work on my gfx1031 card, I made the same mistake as you.

If I hadn't seen that you also set "HIP_VISIBLE_DEVICES" > 1 as a variable then I wouldn't have known. By removing HIP_VISIBLE_DEVICES from the system variables hipInfo works again.

**Comment by harkgill-amd** [comment]
I'll add this here for future reference if someone stumbles across this issue. The "HIP_VISIBLE_DEVICES" environment variable specifies which devices are exposed to HIP applications, in this case hipInfo. 

The variable should be set in the form of comma separated list, for example `HIP_VISIBLE_DEVICES="0,2"`

This variable is not set by default during the installation. Manually setting the value to "1" hid your GPU from hipInfo.exe causing the error `no ROCm-capable device is detected`. You can find more information on HIP_VISIBLE_DEVICES and other GPU isolation techniques [here](https://rocm.docs.amd.com/en/latest/conceptual/gpu-isolation.html).

**Comment by jtgladiator** [comment]
> I'll add this here for future reference if someone stumbles across this issue. The "HIP_VISIBLE_DEVICES" environment variable specifies which devices are exposed to HIP applications, in this case hipInfo.
> 
> The variable should be set in the form of comma separated list, for example `HIP_VISIBLE_DEVICES="0,2"` This variable is not set by default during the installation so to check the device numbering schema, you run hipInfo on the Windows HIP SDK or rocminfo on Linux.
> 
> Manually setting the value to "1" hid your GPU from hipInfo.exe causing the error `no ROCm-capable device is detected`. You can find more information on HIP_VISIBLE_DEVICES and other GPU isolation techniques [here](https://rocm.docs.amd.com/en/latest/conceptual/gpu-isolation.html).

This just fixed it for me too. Thank you @harkgill-amd and @V6ser

**Comment by MuketTNT** [comment]
> 如果有人偶然发现这个问题，我会在这里添加它以供将来参考。“HIP_VISIBLE_DEVICES”环境变量指定哪些设备向 HIP 应用程序公开，在本例中为 hipInfo。
> 
> 变量应以逗号分隔列表的形式设置，例如 `HIP_VISIBLE_DEVICES="0,2"` 默认情况下，安装期间不会设置此变量，因此若要检查设备编号架构，请在 Windows HIP SDK 上运行 hipInfo 或在 Linux 上运行 rocminfo。
> 
> 手动将值设置为“1”会隐藏您的 GPU hipInfo.exe导致错误 `no ROCm-capable device is detected`。您可以在此处找到有关HIP_VISIBLE_DEVICES和其他 GPU 隔离技术的更多信息 [here](https://rocm.docs.amd.com/en/latest/conceptual/gpu-isolation.html)。
thank u for this,l do it now

**Comment by chandujr** [comment]
I did set the variable `export ROCR_VISIBLE_DEVICES=0,2` but even after that I'm getting the error:
```
HIP failure 100: no ROCm-capable device is detected ; GPU=-1 ;
```

Even though these returned proper values:
```
> python3 -c 'import torch; print(torch.cuda.device_count())'
2

> python3 -c 'import torch; print(torch.cuda.get_device_name(0))'
AMD Radeon RX 6800M

> python3 -c 'import torch; print(torch.cuda.get_device_name(1))'
AMD Radeon Graphics

> python3 -c 'import torch; print(hasattr(torch.version, \'hip\'))'
True
```

**Comment by harkgill-amd** [comment]
@chandujr, that's odd - could you file a new ticket with this information + 

- command you're running when you encounter the error
- ROCm and or HIP SDK release(s) you have installed on your system
- Output of initial erroring command without the `ROCR_VISBILE_DEVICES` env variable set

**Comment by chandujr** [comment]
@harkgill-amd This particular problem for me got resolved. It happened because Actually I was checking this inside a venv and I installed the wrong onnxruntime-rocm package. My system ROCm version is 6.3.1 and after installing the proper onnxruntime-rocm package for that, it is working now.
