### ISSUE TITLE
Rocm 6.0: amdgpu.ids: No such file or directory 

### ISSUE THREAD

**Issue by Loungagna** [ROCm/ROCm#2961]
### Problem Description

When pytorch 2.3.0.dev20240312+rocm6.0 is used, only the Laptop Graphic card is active:
`>>> torch.cuda.is_available()
True
>>> torch.cuda.device_count()
1
>>> torch.cuda.device(0)
<torch.cuda.device object at 0x7f0ff2000830>
>>> torch.cuda.get_device_name(0)
'AMD Radeon Graphics'`

whereas on the same machine, on the same linux, with the same user when pytorch 2.2.1+rocm5.7 is used, then the proper GPU is found:
`>>> torch.cuda.is_available()
True
>>> torch.cuda.device_count()
1
>>> torch.cuda.current_device()
0
>>> torch.cuda.device(0)
<torch.cuda.device object at 0x7f913c3b2360>
>>> torch.cuda.get_device_name(0)
'AMD Radeon RX 7700S'`

### Operating System

OS: NAME="Fedora Linux" VERSION="40 (Workstation Edition Prerelease)"

### CPU

CPU: model name	: AMD Ryzen 7 7840HS w/ Radeon 780M Graphics

### GPU

AMD Radeon RX 7900 XTX

### ROCm Version

ROCm 6.0.0

### Steps to Reproduce

import torch;

(Notice the error message: 
amdgpu.ids: No such file or directory
amdgpu.ids: No such file or directory

torch.cuda.device(0);
torch.cuda.get_device_name(0);

expected:
'AMD Radeon RX 7700S'

issue is Rocm 6.0 reports:
'AMD Radeon Graphics'

it is the motherboard graphic card, not the expensive GPU added to the Framework laptop.

### (Optional for Linux users) Output of /opt/rocm/bin/rocminfo --support

ROCk module is loaded
=====================
HSA System Attributes
=====================
Runtime Version:         1.1
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE
System Endianness:       LITTLE
Mwaitx:                  DISABLED
DMAbuf Support:          YES

==========
HSA Agents
==========
*******
Agent 1
*******
  Name:                    AMD Ryzen 7 7840HS w/ Radeon 780M Graphics
  Uuid:                    CPU-XX
  Marketing Name:          AMD Ryzen 7 7840HS w/ Radeon 780M Graphics
  Vendor Name:             CPU
  Feature:                 None specified
  Profile:                 FULL_PROFILE
  Float Round Mode:        NEAR
  Max Queue Number:        0(0x0)
  Queue Min Size:          0(0x0)
  Queue Max Size:          0(0x0)
  Queue Type:              MULTI
  Node:                    0
  Device Type:             CPU
  Cache Info:
    L1:                      32768(0x8000) KB
  Chip ID:                 0(0x0)
  ASIC Revision:           0(0x0)
  Cacheline Size:          64(0x40)
  Max Clock Freq. (MHz):   5137
  BDFID:                   0
  Internal Node ID:        0
  Compute Unit:            16
  SIMDs per CU:            0
  Shader Engines:          0
  Shader Arrs. per Eng.:   0
  WatchPts on Addr. Ranges:1
  Features:                None
  Pool Info:
    Pool 1
      Segment:                 GLOBAL; FLAGS: FINE GRAINED
      Size:                    32021008(0x1e89a10) KB
      Allocatable:             TRUE
      Alloc Granule:           4KB
      Alloc Alignment:         4KB
      Accessible by all:       TRUE
    Pool 2
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    32021008(0x1e89a10) KB
      Allocatable:             TRUE
      Alloc Granule:           4KB
      Alloc Alignment:         4KB
      Accessible by all:       TRUE
    Pool 3
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED
      Size:                    32021008(0x1e89a10) KB
      Allocatable:             TRUE
      Alloc Granule:           4KB
      Alloc Alignment:         4KB
      Accessible by all:       TRUE
  ISA Info:
*******
Agent 2
*******
  Name:                    gfx1102
  Uuid:                    GPU-XX
  Marketing Name:          AMD Radeon RX 7700S
  Vendor Name:             AMD
  Feature:                 KERNEL_DISPATCH
  Profile:                 BASE_PROFILE
  Float Round Mode:        NEAR
  Max Queue Number:        128(0x80)
  Queue Min Size:          64(0x40)
  Queue Max Size:          131072(0x20000)
  Queue Type:              MULTI
  Node:                    1
  Device Type:             GPU
  Cache Info:
    L1:                      32(0x20) KB
    L2:                      2048(0x800) KB
  Chip ID:                 29824(0x7480)
  ASIC Revision:           0(0x0)
  Cacheline Size:          64(0x40)
  Max Clock Freq. (MHz):   2208
  BDFID:                   768
  Internal Node ID:        1
  Compute Unit:            32
  SIMDs per CU:            2
  Shader Engines:          2
  Shader Arrs. per Eng.:   2
  WatchPts on Addr. Ranges:4
  Coherent Host Access:    FALSE
  Features:                KERNEL_DISPATCH
  Fast F16 Operation:      TRUE
  Wavefront Size:          32(0x20)
  Workgroup Max Size:      1024(0x400)
  Workgroup Max Size per Dimension:
    x                        1024(0x400)
    y                        1024(0x400)
    z                        1024(0x400)
  Max Waves Per CU:        32(0x20)
  Max Work-item Per CU:    1024(0x400)
  Grid Max Size:           4294967295(0xffffffff)
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)
    y                        4294967295(0xffffffff)
    z                        4294967295(0xffffffff)
  Max fbarriers/Workgrp:   32
  Packet Processor uCode:: 550
  SDMA engine uCode::      16
  IOMMU Support::          None
  Pool Info:
    Pool 1
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED
      Size:                    8372224(0x7fc000) KB
      Allocatable:             TRUE
      Alloc Granule:           4KB
      Alloc Alignment:         4KB
      Accessible by all:       FALSE
    Pool 2
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    8372224(0x7fc000) KB
      Allocatable:             TRUE
      Alloc Granule:           4KB
      Alloc Alignment:         4KB
      Accessible by all:       FALSE
    Pool 3
      Segment:                 GROUP
      Size:                    64(0x40) KB
      Allocatable:             FALSE
      Alloc Granule:           0KB
      Alloc Alignment:         0KB
      Accessible by all:       FALSE
  ISA Info:
    ISA 1
      Name:                    amdgcn-amd-amdhsa--gfx1102
      Machine Models:          HSA_MACHINE_MODEL_LARGE
      Profiles:                HSA_PROFILE_BASE
      Default Rounding Mode:   NEAR
      Default Rounding Mode:   NEAR
      Fast f16:                TRUE
      Workgroup Max Size:      1024(0x400)
      Workgroup Max Size per Dimension:
        x                        1024(0x400)
        y                        1024(0x400)
        z                        1024(0x400)
      Grid Max Size:           4294967295(0xffffffff)
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)
        y                        4294967295(0xffffffff)
        z                        4294967295(0xffffffff)
      FBarrier Max Size:       32
*** Done ***

### Additional Information

The GPU not recognized by 6.0 is #0 AMD Radeon RX 7700S.

**Comment by nartmada** [comment]
Hi @Loungagna, thanks for filing the ticket.  Can you please share your laptop brand/model?  Thanks.

**Comment by vstempen** [comment]
@Loungagna , Can you please run  "pip show torch". It will show the path to site-packages (for you must be something like "Location: .local/lib/python3.12/sites-packages/"). From that path find torch/share/libdrm/amdgpu.ids. If the file exists, can you find AMD Radeon RX 7700S? Does it match your device id? If you cannot find amdgpu.ids in that location, can you run "find  .local/lib/python3.12/sites-packages/torch -name amdgpu.ids". Thanks.

**Comment by vstempen** [comment]
That's you 2.2.1+rocm5.7 case, which you have no problem with. Can you do the same for 2.3.0.dev20240312+rocm6.0?

**Comment by vstempen** [comment]
What if you just run  print(torch.__file__) from python. Can you also run "grep "RX 7700S" /opt/amdgpu/share/libdrm/amdgpu.ids" if the file exists. For me, if I delete /opt/amdgpu/share/libdrm/amdgpu.ids the device name is taken from python's site-packages/torch/share/libdrm/amdgpu.ids. If I delete both, I'll can reproduce the problem:
>>> import torch
amdgpu.ids: No such file or directory
>>> torch.cuda.get_device_name(0)
'AMD Radeon Graphics'

**Comment by vstempen** [comment]
So, it seems you don't have user-mode driver installed. It's Red Hat, right? Try to run "rpm -qa | grep libdrm" to see if it's installed. If you did have it installed, it would take preference. Torch seems to have it's own user mode components to interact with kernel driver. But in your defective python it seems not being able to work properly. Is it just device identification that is failing or everything else failing too, like creating a tensor on GPU?

**Comment by vstempen** [comment]
So, it seems there is no issue AMD can help to resolve in this case. Should we close the ticket?

**Comment by vstempen** [comment]
I have just built pyton12 on new RHEL system with rocm-6.1.0 installed. Installed pytorch (pip3.12 install --pre --force-reinstall torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/rocm6.0/) . And I can see torch.cuda.get_device_name(0) gives me correct product name. Maybe you can try clean install first.

**Comment by nartmada** [comment]
@Loungagna, any update with @vstempen's suggestion of doing a clean install first?

**Comment by nartmada** [comment]
Closing the ticket.  @Loungagna, please re-open if you still see the issue with a clean install.  Thanks.

**Comment by teleprint-me** [comment]
You can use `mlocate` to see if the GPU ids are available. This is a 3rd party package supported by most distros.

I run into this issue every time I do a clean install even though I have everything I need.

```sh
locate amdgpu.ids
/usr/share/libdrm/amdgpu.ids
```

But PyTorch looks elsewhere for this.

```sh
python -c "import torch; print(torch.cuda.get_arch_list())"
/opt/amdgpu/share/libdrm/amdgpu.ids: No such file or directory
```

Just as a sanity check, I usually just check for the files existance.

```sh
file /opt/amdgpu/share/libdrm/amdgpu.ids
/opt/amdgpu/share/libdrm/amdgpu.ids: cannot open `/opt/amdgpu/share/libdrm/amdgpu.ids' (No such file or directory)
```

Because ROCm is installed into a non-conventional path, the binaries, libraries, etc. are never registered even though everything that is required already exists.

This means usually having to dig through a bunch of docs, references, posts, issues, etc. just to figure out which environment variables I need. This is non-trivial even though it should be.

```sh
# Only enable if using ROCm
export ROCM_PATH=/opt/rocm
export ROCM_HOME=/opt/rocm

# ROCm device visibility
export HIP_VISIBLE_DEVICES=0
export ROCR_VISIBLE_DEVICES=0
export TRITON_USE_ROCM=1

# ROCm device override
export AMDGPU_TARGETS="gfx1100"
export HCC_AMDGPU_TARGET="gfx1100"
export PYTORCH_ROCM_ARCH="gfx1100"
export HSA_OVERRIDE_GFX_VERSION="11.0.0"  # Ensure correct RDNA3 detection

# Optional: Disable hipBLASLt if issues occur
export USE_HIPBLASLT=0
export TORCH_BLAS_PREFER_HIPBLASLT=0

# PyTorch ROCm Memory Management
export PYTORCH_ALLOC_CONF="expandable_segments:False,garbage_collection_threshold:0.8"

# ROCm path export
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/rocm/lib
export PATH=$PATH:/opt/rocm:/opt/rocm/lib:/opt/rocm/share:/opt/rocm/bin
```

The only way to figure out which environment variables are valid are to use `rocminfo` and `rocm_agent_enumerator`. `rocm_agent_enumerator` tells me which version I have registered. 

The versioning is unclear and usually I just brute force my way through it until I figure it out since there's no consistent schema for it.

I'm not sure if there's a variable I can set to remedy where the device ids are set.

e.g.

```sh
LIBAMDGPU_ID_PATH=/usr/share/libdrm/amdgpu.ids
```

versus just doing

```sh
# Create the directory that torch expects
sudo mkdir -p /opt/amdgpu/share/libdrm

# Point that directory to the real file
sudo ln -s /usr/share/libdrm/amdgpu.ids /opt/amdgpu/share/libdrm/amdgpu.ids
```

Symlinking is probably the easiest method, but I'm not sure how reliable or flexible that is.

As far as I can tell, this is unresolved issue. I'm posting this here for others that encounter similar issues. I wouldn't mind any feedback regarding my solutions to resolving these issues.

**Comment by dcunited001** [comment]
thanks for the documentation of environment variables. 

i'm on nixos. my configuration is largely irrelavant here. 

when i run with `torchvision` from nixpkgs, i don't see the warning. just based on my profile's build, it doesn't seem that the `amdgpu.ids` file is necessary. it depends on the build (i think? also it could be using `rocm-core`?)

when i run with `torchvision` i get the warning and then it fails because it miopen can't find `math.h` for `#include <math.h>` 

```shell
locate amdgpu.ids
# the only relevant result:
# /data/lang/python/_torch/uvtorch/.venv/lib/python3.13/site-packages/torch/share/libdrm/amdgpu.ids
```

the only reference to this `amdgpu.ids` in nixpkgs is in the [fastfetch package](https://github.com/NixOS/nixpkgs/issues/308849), where that build's cmake exposes `CUSTOM_AMDGPU_IDS_PATH`. that's a static file path though, so i just copied it. 

I still have something wrong with my setup though

**Comment by nevion** [comment]
/usr/share/libdrm/amdgpu.ids on opensuse 16.0 so maybe should add it to a list of probe locations and not break/warning if in the old /opt/amdgpu paths

**Comment by magnusahlden** [comment]
> You can use `mlocate` to see if the GPU ids are available. This is a 3rd party package supported by most distros.
> 
> I run into this issue every time I do a clean install even though I have everything I need.
> 
> locate amdgpu.ids
> /usr/share/libdrm/amdgpu.ids
> 
> But PyTorch looks elsewhere for this.
> 
> python -c "import torch; print(torch.cuda.get_arch_list())"
> /opt/amdgpu/share/libdrm/amdgpu.ids: No such file or directory
> 
> Just as a sanity check, I usually just check for the files existance.
> 
> file /opt/amdgpu/share/libdrm/amdgpu.ids
> /opt/amdgpu/share/libdrm/amdgpu.ids: cannot open `/opt/amdgpu/share/libdrm/amdgpu.ids' (No such file or directory)
> 
> Because ROCm is installed into a non-conventional path, the binaries, libraries, etc. are never registered even though everything that is required already exists.
> 
> This means usually having to dig through a bunch of docs, references, posts, issues, etc. just to figure out which environment variables I need. This is non-trivial even though it should be.
> 
> # Only enable if using ROCm
> export ROCM_PATH=/opt/rocm
> export ROCM_HOME=/opt/rocm
> 
> # ROCm device visibility
> export HIP_VISIBLE_DEVICES=0
> export ROCR_VISIBLE_DEVICES=0
> export TRITON_USE_ROCM=1
> 
> # ROCm device override
> export AMDGPU_TARGETS="gfx1100"
> export HCC_AMDGPU_TARGET="gfx1100"
> export PYTORCH_ROCM_ARCH="gfx1100"
> export HSA_OVERRIDE_GFX_VERSION="11.0.0"  # Ensure correct RDNA3 detection
> 
> # Optional: Disable hipBLASLt if issues occur
> export USE_HIPBLASLT=0
> export TORCH_BLAS_PREFER_HIPBLASLT=0
> 
> # PyTorch ROCm Memory Management
> export PYTORCH_ALLOC_CONF="expandable_segments:False,garbage_collection_threshold:0.8"
> 
> # ROCm path export
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/rocm/lib
> export PATH=$PATH:/opt/rocm:/opt/rocm/lib:/opt/rocm/share:/opt/rocm/bin
> 
> The only way to figure out which environment variables are valid are to use `rocminfo` and `rocm_agent_enumerator`. `rocm_agent_enumerator` tells me which version I have registered.
> 
> The versioning is unclear and usually I just brute force my way through it until I figure it out since there's no consistent schema for it.
> 
> I'm not sure if there's a variable I can set to remedy where the device ids are set.
> 
> e.g.
> 
> LIBAMDGPU_ID_PATH=/usr/share/libdrm/amdgpu.ids
> 
> versus just doing
> 
> # Create the directory that torch expects
> sudo mkdir -p /opt/amdgpu/share/libdrm
> 
> # Point that directory to the real file
> sudo ln -s /usr/share/libdrm/amdgpu.ids /opt/amdgpu/share/libdrm/amdgpu.ids
> 
> Symlinking is probably the easiest method, but I'm not sure how reliable or flexible that is.
> 
> As far as I can tell, this is unresolved issue. I'm posting this here for others that encounter similar issues. I wouldn't mind any feedback regarding my solutions to resolving these issues.

Thanks for sharing this. I'm on arch with a AMD a395+ (great cpu/gpu combo) that didn't work until I tried this work around. now it works perfectly fine with torch. @teleprint-me thanks for sharing. much appriciated!

**Comment by Numeri** [comment]
@teleprint-me Today I found the env var `AMDGPU_ASIC_ID_TABLE_PATHS` inside of the `libdrm_amdgpu.so` that shipped with `torch==2.12.0+rocm7.2`. Setting it to the directory containing `amdgpu.ids` works :)
