### ISSUE TITLE
[Issue]: Comfy_UI hipblasLT not supported for Radeon 7900XT and HSA_STATUS_ERROR_OUT_OF_REGISTERS error

### ISSUE THREAD

**Issue by fluidnumerics-joe** [ROCm/ROCm#4437]
### Problem Description

I'm reporting this issue on behalf of the OP from [this post on discuss.pytorch.org](https://discuss.pytorch.org/t/comfy-ui-attempting-to-use-hipblaslt-on-a-unsupported-architecture/215776).
I've copied the stdout/stderr here

```
Total VRAM 20464 MB, total RAM 63432 MB
pytorch version: 2.6.0.dev20241122+rocm6.2
Set vram state to: NORMAL_VRAM
Device: cuda:0 Radeon RX 7900 XT : native
Using sub quadratic optimization for attention, if you have memory or speed issues try using: --use-split-cross-attention
[Prompt Server] web root: /home/sersys/pyproj/ComfyUI-0.3.12/web

Import times for custom nodes:
   0.0 seconds: /home/sersys/pyproj/ComfyUI-0.3.12/custom_nodes/websocket_image_save.py

Starting server

To see the GUI go to: http://127.0.0.1:8188
got prompt
model weight dtype torch.float16, manual cast: None
model_type EPS
Using split attention in VAE
Using split attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.float32
CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cpu, dtype: torch.float16
Requested to load SDXLClipModel
loaded completely 9.5367431640625e+25 1560.802734375 True
/home/sersys/pyproj/ComfyUI-0.3.12/comfy/ops.py:64: UserWarning: Attempting to use hipBLASLt on an unsupported architecture! Overriding blas backend to hipblas (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:296.)
  return torch.nn.functional.linear(input, weight, bias)
Requested to load SDXL
loaded completely 9.5367431640625e+25 4897.0483474731445 True
  0%|                                                                | 0/20 [00:00<?, ?it/s]:0:rocdevice.cpp            :2984: 93862815501 us: [pid:318562 tid:0x7f122e5ff640] Callback: Queue 0x7f0ed8000000 aborting with error : HSA_STATUS_ERROR_OUT_OF_REGISTERS: Kernel has requested more VGPRs than are available on this agent code: 0x2d
Aborted (core dumped)
```

There are two issues here that the OP is concerned about : 

*The first is a non-fatal warning*
There appears to be a warning issued by pytorch stating that the Radeon RX 7900XT is not supported by the HIPBlasLT backend. There is no ROCm documentation that indicates this GPU is not supported by HIPBlasLT; in fact the [compatibility matrix](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html#supported-gpus) suggests it is supported. Is this an issue with Pytorch or is this GPU not actually supported in hipblaslt ?

This being said, it does appear that they are not on a [supported Linux kernel](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html#supported-operating-systems) ( 6.12.9 ); however, no errors appear to indicate specifically that this is the culprit.

*The second issue appears fatal*
During the execution of `torch.nn.functional.linear`, the code aborts with an `HSA_STATUS_ERROR_OUT_OF_REGISTERS` error. I suspect this an issue with MIOpen; perhaps it's targeting the wrong architecture and over-allocating vgpr ? My understanding is that some of these torch functions are compiled on the fly during the first execution and this is handled by MIOpen. Any guidance you can provide on further diagnosing the problem here would be great.

### Operating System

Debian GNU/Linux 12

### CPU

AMD Ryzen 9 7900X 12-Core Processor

### GPU

Radeon 7900 XT

### ROCm Version

ROCm 6.2.0

### ROCm Component

Pytorch, MIOpen

**Comment by fluidnumerics-joe** [comment]
This other discussion may be related to the first (non-fatal) issue.

https://discuss.pytorch.org/t/rocm6-2-build-of-pytroch-is-faling-for-llama3-2-vision-model/211622

Here, the users report that another supported AMD Radeon GPU (in this case the Radeon Pro W7900) is being marked as unsupported in hipblaslt . Let me know if you'd like to see another ticket opened for this one.

**Comment by fluidnumerics-joe** [comment]
A few other potentially related issues : 

* https://github.com/pytorch/pytorch/issues/138067
* https://github.com/ROCm/hipBLASLt/issues/1243

**Comment by fluidnumerics-joe** [comment]
Hey @tcgu-amd - This is incredibly helpful. I'll feed back on this and see if we can help get resolution on this.

**Comment by fluidnumerics-joe** [comment]
[OP claims they updated ROCm to v 6.3.2 ](https://discuss.pytorch.org/t/comfy-ui-attempting-to-use-hipblaslt-on-a-unsupported-architecture/215776/6) and still encounter the unsupported gpu in `hipblaslt` issue . From the output from comfy_ui, it appears that it is picking up the ROCm 6.3 install of pytorch 2.7.0 ..

**Comment by tcgu-amd** [comment]
@fluidnumerics-joe Interesting...Based on the LOC from the newest error log the change should've made it into the build. I will also try to investigate a bit more on my end. Thanks!

**Comment by tcgu-amd** [comment]
@fluidnumerics-joe Just in case, it might be helpful to manually verify the ROCm version with `torch.version.hip`

**Comment by garrettbyrd** [comment]
I was able to test with the specified environment, `torch==2.7.0.dev20250206+rocm6.3` with ROCm 6.3.2.

I did not test on a Radeon RX 7900XT, but I did test on a Radeon PRO W7800, which is also `gfx1100`.

Testing with the [minimal reproducer](https://github.com/pytorch/pytorch/issues/138067#issuecomment-2417505527), I was not able to reproduce the unsupported architecture warning.

I also tested using the latest nightly build of pytorch (`torch==2.7.0.dev20250302+rocm6.3`) and this also ran without raising the warning.

Finally, I also tested on a Radeon RX 7600 with `HSA_OVERRIDE_GFX_VERSION=11.0.0` and this also ran without raising the warning.

**Comment by fluidnumerics-joe** [comment]
Thanks @garrettbyrd for adding this - I'm suspecting this is a situation of python environment management issues, more than ROCm. However, we're not looking exactly at a Radeon 7900 XT.

@tcgu-amd Are you able to test the minimal reproducer that Garrett shared on a Radeon 7900XT or are we going to have to pick one up for our cluster ?

**Comment by tcgu-amd** [comment]
> Thanks [@garrettbyrd](https://github.com/garrettbyrd) for adding this - I'm suspecting this is a situation of python environment management issues, more than ROCm. However, we're not looking exactly at a Radeon 7900 XT.
> 
> [@tcgu-amd](https://github.com/tcgu-amd) Are you able to test the minimal reproducer that Garrett shared on a Radeon 7900XT or are we going to have to pick one up for our cluster ?

Hi @fluidnumerics-joe, @garrettbyrd yes, I was just able finish testing. And no, both `export TORCH_BLAS_PREFER_HIPBLASLT=1` and `export TORCH_BLAS_PREFER_HIPBLASLT=0` do not generate warnings on RX 7900XT

**Comment by tcgu-amd** [comment]
@fluidnumerics-joe @garrettbyrd, I guess there are two things the OP can check to help debug

1. Use `torch.version.hip` to verify if the torch version is indeed >= 6.3
2. Use ` torch.cuda.get_device_properties()` to verify if the `gcnArchName=='gfx1100'`

If both are correct, then something likely is wrong with how ComfyUI is using torch/python.

**Comment by fluidnumerics-joe** [comment]
Thanks @tcgu-amd for testing that out. I'll relay this back to OP

**Comment by fluidnumerics-joe** [comment]
Hey @tcgu-amd - I'm got some feedback on this one. 

[Here is the output with `AMD_LOG_LEVEL=3` and `HSAKMT_DEBUG_LEVEL=4 `](https://github.com/user-attachments/files/19131804/pyver.txt)

Here is OP's output of

```python
print(torch.version.hip)
print(torch.cuda.get_device_properties())
```

```
6.3.42131-fa1d09cbd
_CudaDeviceProperties(name='Radeon RX 7900 XT', major=11, minor=0, gcnArchName='gfx1100', total_memory=20464MB, multi_processor_count=42, uuid=30303033-6430-3863-3030-303030303030, L2_cache_size=6MB)
```

Here's the [Comfy_UI workflow file](https://github.com/user-attachments/files/19131822/Default.Workflow.json); we're going to take a look at this from Comfy_UI on our system.

Last, OP did mention that their latest attempt was using AMD's Pytorch Docker image (following [these instructions](https://rocm.docs.amd.com/projects/install-on-linux/en/develop/install/3rd-party/pytorch-install.html)) . Also, they confirmed their host system is Debian with Linux kernel 6.12.12-amd64 , which I notice is a minor version ahead of the latest supported Linux kernel in the [supported operating system compatibility matrix](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html#supported-operating-systems)

**Comment by tcgu-amd** [comment]
@fluidnumerics-joe Thanks for the update! Interestingly, hip runtime seems to be picking up 2 GPUs on the device, one if gfx1100 and another gfx1036, as can be seen from this part of the logs

 ```
 :3:rocdevice.cpp            :1803: 133669785949d us:  HMM support: 0, XNACK: 0, Direct host access: 0
:3:rocdevice.cpp            :1805: 133669785950d us:  Max SDMA Read Mask: 0x3, Max SDMA Write Mask: 0x3
:3:rocdevice.cpp            :235 : 133669786607d us:  Numa selects cpu agent[0]=0x41b424a0(fine=0x3dcb4590,coarse=0x448ef230) for gpu agent=0x44f26d20 CPU<->GPU XGMI=0
:3:rocsettings.cpp          :287 : 133669786610d us:  Using dev kernel arg wa = 0
:3:rocdevice.cpp            :1801: 133669786959d us:  Gfx Major/Minor/Stepping: 10/3/6
:3:rocdevice.cpp            :1803: 133669786962d us:  HMM support: 0, XNACK: 0, Direct host access: 0
:3:rocdevice.cpp            :1805: 133669786963d us:  Max SDMA Read Mask: 0x1, Max SDMA Write Mask: 0x1
:3:hip_context.cpp          :49  : 133669787646d us:  Direct Dispatch: 1
```
This seems like could be the culprit.

**Comment by fluidnumerics-joe** [comment]
@tcgu-amd - The gfx1036 appears to be an iGPU with Ryzen 7000 series CPUs. I suspect they should disable the iGPU : https://rocm.docs.amd.com/projects/radeon/en/latest/docs/prerequisites.html

**Comment by tcgu-amd** [comment]
> [@tcgu-amd](https://github.com/tcgu-amd) - The gfx1036 appears to be an iGPU with Ryzen 7000 series CPUs. I suspect they should disable the iGPU : https://rocm.docs.amd.com/projects/radeon/en/latest/docs/prerequisites.html

Makes sense.

**Comment by fluidnumerics-joe** [comment]
Hey @tcgu-amd - I've attached logs of the same execution, but with the iGPU disabled. This appears to fix the warning related to hipblaslt on an unsupported GPU. However, we're still hitting the `HSA_STATUS_ERROR_OUT_OF_REGISTERS`.

One thing I did notice is that OP is using Python 3.12. This is required for the Comfy_UI package. However, the pytorch installation is using the distributed wheels, which are built against Python 3.10 . [ROCm docs](https://rocm.docs.amd.com/projects/radeon/en/latest/docs/install/wsl/install-pytorch.html#install-methods) indicate that this configuration won't work


>   Important! These specific ROCm WHLs are built for Python 3.10, and will not work on other versions of Python.

I've fed back that they can uninstall pytorch and [build pytorch from source](https://github.com/pytorch/pytorch/?tab=readme-ov-file#amd-rocm-support) . You may know that this is a time-intensive process, which is why I've also opened up https://github.com/ROCm/ROCm/issues/4473 

This is not the only person I've found looking to use Comfy_UI under WSL2 with Radeon GPUs.

**Comment by james-banks** [comment]
> However, the pytorch installation is using the distributed wheels, which are built against Python 3.10 . [ROCm docs](https://rocm.docs.amd.com/projects/radeon/en/latest/docs/install/wsl/install-pytorch.html#install-methods) indicate that this configuration won't work
> 
> 
> >   Important! These specific ROCm WHLs are built for Python 3.10, and will not work on other versions of Python.

I believe that notice is outdated. The actual links they provide (and many of the wheels in the repo) are for Python 3.12 (as seen by the `cp312` in the file names): 

> https://repo.radeon.com/rocm/manylinux/rocm-rel-6.3.4/torchaudio-2.4.0%2Brocm6.3.4.git69d40773-cp312-cp312-linux_x86_64.whl

**Comment by tcgu-amd** [comment]
> Hey [@tcgu-amd](https://github.com/tcgu-amd) - I've attached logs ( [igpudisabled.txt](https://github.com/user-attachments/files/19166334/igpudisabled.txt) ) of the same execution, but with the iGPU disabled. This appears to fix the warning related to hipblaslt on an unsupported GPU. However, we're still hitting the `HSA_STATUS_ERROR_OUT_OF_REGISTERS`.
> 
> One thing I did notice is that OP is using Python 3.12. This is required for the Comfy_UI package. However, the pytorch installation is using the distributed wheels, which are built against Python 3.10 . [ROCm docs](https://rocm.docs.amd.com/projects/radeon/en/latest/docs/install/wsl/install-pytorch.html#install-methods) indicate that this configuration won't work
> 
> > Important! These specific ROCm WHLs are built for Python 3.10, and will not work on other versions of Python.
> 
> I've fed back that they can uninstall pytorch and [build pytorch from source](https://github.com/pytorch/pytorch/?tab=readme-ov-file#amd-rocm-support) . You may know that this is a time-intensive process, which is why I've also opened up [#4473](https://github.com/ROCm/ROCm/issues/4473)
> 
> This is not the only person I've found looking to use Comfy_UI under WSL2 with Radeon GPUs.

Oh the user is using WSL2? I was under the impression that they were using native linux...

In this case, setting up ROCm on WSL2 works differently from on native Linux, please follow this guide to [install the latest supported ROCm on Radeon](https://rocm.docs.amd.com/projects/radeon/en/latest/docs/install/wsl/install-radeon.html), then [this guide for installing pytorch](https://rocm.docs.amd.com/projects/radeon/en/latest/docs/install/wsl/install-pytorch.html).

Thanks!

**Comment by fluidnumerics-joe** [comment]
Apologies, I've gotten this mixed up with other Comfy_UI issues we're tracking. This particular one is on Debian.

**Comment by Sersys** [comment]
Hello, I'm OP @fluidnumerics-joe was posting on behalf.

I just want to add a side note, I'm not sure if it's relevant but I'm having issues running Ollama and ffmpeg using av1_amf as well. Both give me the error that they are unable to allocate memory on the GPU. I have a feeling it's the same Rocm issue and probably not a pytorch or comfy_ui fault. Unfortunately I got very little to no help from Ollama and ffmpeg so I can't confirm.

**Comment by tcgu-amd** [comment]
Hi @Sersys, thanks for reaching out to us! Just wondering, do you know if the issues you encountered can be reproduced on one of our supported kernel versions (e.g. 6.11). There has been a few bugs reported to us related to kernel 6.12, just wanted to see if we can isolate the cause here. Thanks!

**Comment by fluidnumerics-joe** [comment]
Hey @Sersys - Have you been able to try reproducing the error on a supported kernel ?

**Comment by Sersys** [comment]
I've never installed a custom kernel before, I always used the default kernel the distro was shipped with. I had to read upon it to make sure changing kernels is something I would be able to do. I also had to free up a spare HDD, I can't risk losing my daily drive. I'm still trying to figure out how Grub works because last time I've installed a different distro on a separate hard drive my daily driver failed to boot, I've managed to fix it eventually but I would like to avoid it from happening again. I also have some other things to attend to, I should probably able to get back to you in a day or two, I haven't forgotten about it. My apologies for the delay.

**Comment by fluidnumerics-joe** [comment]
@Sersys - this is fantastic news! I'll drop a comment back on discourse. I'm glad that this resolved the issue.

**Comment by Sersys** [comment]
> [@Sersys](https://github.com/Sersys) - this is fantastic news! I'll drop a comment back on discourse. I'm glad that this resolved the issue.

I don't want to look ungrateful, far from it, I can't thank you enough for the lengths you've gone for me, the reason I haven't closed out the pytorch post is because I thought this experiment was to confirm something and not the final solution.  I take it it's not possible to run rocm on a 6.12 or 6.13 kernel debian then?

**Comment by fluidnumerics-joe** [comment]
@Sersys , that's correct. It appears that you do indeed need to use a supported [Linux distribution and kernel](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html#supported-distributions) to use ROCm reliably. I understand it may not be the answer you wanted, but it is the answer.

I suspect that AMD is actively working on support for more recent linux kernels, but as of today this is the answer.

**Comment by Sersys** [comment]
Understandable. Thank you for everyone's help. I appreciate you all taking your time for me.
